# org: my-org
# app: my-app
service: leer-anuncios
frameworkVersion: '2 || 3'
app: serverless-test

provider:
  name: aws
  region: eu-west-1
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  status:
    handler: handler.status
    events:
      - httpApi:
          path: /
          method: get
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: post
